import mongoose from 'mongoose';

const progressReportSchema = new mongoose.Schema(
  {
    childId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Child',
      required: true,
      index: true,
    },
    // Report Type
    reportType: {
      type: String,
      enum: ['weekly', 'monthly', 'quarterly', 'yearly', 'custom'],
      required: true,
    },
    // Report Period
    periodStart: {
      type: Date,
      required: true,
    },
    periodEnd: {
      type: Date,
      required: true,
    },
    // Overall Progress Summary
    overallProgress: {
      score: { type: Number, min: 0, max: 100 },
      trend: {
        type: String,
        enum: ['improving', 'stable', 'declining', 'variable'],
      },
      summary: String,
    },
    // Goals Progress
    goalsProgress: [
      {
        goalId: { type: mongoose.Schema.Types.ObjectId, ref: 'TherapyGoal' },
        goalTitle: String,
        progressPercentage: { type: Number, min: 0, max: 100 },
        status: String,
        milestones: [
          {
            milestone: String,
            achieved: Boolean,
            achievedDate: Date,
          },
        ],
      },
    ],
    // Behavior Analysis
    behaviorAnalysis: {
      totalLogs: Number,
      positiveCount: Number,
      negativeCount: Number,
      neutralCount: Number,
      trends: [
        {
          category: String,
          trend: String,
          frequency: Number,
        },
      ],
      triggers: [
        {
          trigger: String,
          frequency: Number,
          impact: String,
        },
      ],
    },
    // Therapy Sessions Summary
    therapySessions: {
      total: Number,
      completed: Number,
      missed: Number,
      attendanceRate: Number, // percentage
      averageProgress: Number,
      sessionsByType: [
        {
          type: String,
          count: Number,
          averageProgress: Number,
        },
      ],
    },
    // Medication Compliance
    medicationCompliance: {
      totalDoses: Number,
      taken: Number,
      missed: Number,
      complianceRate: Number, // percentage
      medications: [
        {
          name: String,
          complianceRate: Number,
        },
      ],
    },
    // Routine Adherence
    routineAdherence: {
      routinesFollowed: Number,
      totalRoutines: Number,
      adherenceRate: Number, // percentage
      mostCompletedActivities: [
        {
          activity: String,
          completionRate: Number,
        },
      ],
    },
    // Milestones Achieved
    milestones: [
      {
        title: String,
        category: String,
        achievedDate: Date,
        description: String,
      },
    ],
    // Recommendations
    recommendations: [
      {
        category: String,
        recommendation: String,
        priority: {
          type: String,
          enum: ['low', 'medium', 'high', 'urgent'],
        },
      },
    ],
    // Charts Data (stored as JSON)
    chartsData: {
      progressOverTime: [
        {
          date: Date,
          score: Number,
          category: String,
        },
      ],
      behaviorTrends: [
        {
          date: Date,
          positive: Number,
          negative: Number,
          neutral: Number,
        },
      ],
      goalProgress: [
        {
          goalId: mongoose.Schema.Types.ObjectId,
          date: Date,
          progress: Number,
        },
      ],
    },
    // Generated By
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // PDF Export
    pdfUrl: {
      type: String, // URL to generated PDF
    },
    pdfGeneratedAt: {
      type: Date,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes
progressReportSchema.index({ childId: 1, periodStart: -1, periodEnd: -1 });
progressReportSchema.index({ childId: 1, reportType: 1, createdAt: -1 });
progressReportSchema.index({ periodStart: 1, periodEnd: 1 });

export default mongoose.model('ProgressReport', progressReportSchema);

